### ISSUE TITLE
Operator signature is occasionally 'null'

### ISSUE THREAD

**Issue by wgjohnson** [burningmantech/ranger-ims-mac#39]
From Incident \#1159:

>2014-08-31 18:43, El Weso:
>request for rangers at rampart from blackrock.
>
>2014-08-31 18:44, (null):
>Rangers to retrieve an anxious participant from rehab room 7

In this example `(null)` should be `El Weso`.

**Comment by wsanchez** [comment]
I never really figured out how this happened, but the server has been changed to reject any report entry data without an associated user and the client is all new and doesn't appear to exhibit such nasty tendencies, so I think we're good now.

**Comment by wsanchez** [comment]
Note that when running the client against a test server using last years' data, the username will obviously still be missing, since it's in the source data.  But no new data should go in like this.

**Comment by wsanchez** [comment]
Please verify with [Incidents 3.0a1] (https://github.com/burningmantech/ranger-ims-mac/releases/tag/v3.0a1).
