### ISSUE TITLE
New incident types

### ISSUE THREAD

**Issue by wgjohnson** [burningmantech/ranger-ims-mac#40]
Request for incident types `911 email` and `missing person`. We have had enough of these types that I think it warrants having a field separate from `admin`.

**Comment by wsanchez** [comment]
Incidents that aren't closed but we're not actively working on them should be put in the "Oh Hold" state.  Maybe those should be filterable… Filed #48 for that.

I need to talk to OODs about the incident type list, but for now I'll add:
* Courtesy Notice
* Missing Person

**Comment by wsanchez** [comment]
Fixed in d4e7d0d3d8f98c0d4ad87ecbb8f7877f5449f273

**Comment by wsanchez** [comment]
Please verify with [Incidents 3.0a1] (https://github.com/burningmantech/ranger-ims-mac/releases/tag/v3.0a1).
