### ISSUE TITLE
Login screen pops up every time I save changes to an incident

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#54]
Happens on new incidents as well as with changes to existing incidents. my login and password are in the fields, but I still have to hit "enter" from the PW field to dismiss the login window.

**Comment by wsanchez** [comment]
Fixed in 0b9fa342db9f3dc55e118ac9462c97475f64dc03

**Comment by wsanchez** [comment]
Fixed in 3.0a3

**Comment by wsanchez** [comment]
woot!
