### ISSUE TITLE
Remote Login doesn't recognize Splinter or Sticky's Username and Password

### ISSUE THREAD

**Issue by splintermathwood** [burningmantech/ranger-ims-mac#55]
Logging in is accepted at first and then the username and Password window comes up again. The first time it takes a while, then it comes back quicker and quicker.

I was able to make a new incident as splinter, but then It won't let me back into the incident.
Same with Sticky

**Comment by splintermathwood** [comment]
Can't edit old data either. Maybe this is a feature?

**Comment by wsanchez** [comment]
Not all users are enabled on khaki-shack… can fix that.  Unsure about other thing…

**Comment by wsanchez** [comment]
Try now
