### ISSUE TITLE
Issues with saving lengthy text from Thursday Swing

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#69]
Reported to me by Tuxedo (left it in a note in the Clubhouse):
"1) I added several notes to incident 671 and 560. I saved the changes. I reopened the reports and the changes were all gone, including the Rangers I added to the incident. Same happened to Nectar with another incident. We were adding long amounts of additional info from the Rangers. We tried braking up the data into several segments and the data was still lost."

**Comment by flwyd** [comment]
I wonder if it would be possible to have text in the free-form area auto-save to a separate data store (maybe local disk) with a way to recover recent work in progress in case something goes wrong like the server going down or the app crashing.

**Comment by wsanchez** [comment]
Pretty sure the described problem doesn't happen now.

@flwyd's note is not crazy (HTML5 local storage, perhaps) for a draft feature, so I'll keep that in mind
