### ISSUE TITLE
Web client login - some people can use their ranger handle, some people need their full email address

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#73]
"I wanted to let you know that I just went to login to the IMS to kick the tires, and the login system asks for your Ranger Handle, but my handle wouldn’t work to login. I had to use the email address I use to login to the Ranger Clubhouse to make that work. So perhaps the login page should ask for an email address, as it does on the clubhouse?" -Tribeca

"The online training login was a little tricky.  It asked for your ranger handle and password, but instead you needed to enter your email and password." -Fortress

Note that just my login worked, I didn't need to enter an email.  -Librarian

**Comment by corprew** [comment]
My handle works as 'Zeitgeist' but not as 'zeitgeist'.   My email address works as 'corprew@corpew.org' and not as 'Corprew@Corprew.Org'.  maybe we just tell folks that capitalization matters.

**Comment by wsanchez** [comment]
capitalization matters.
