### ISSUE TITLE
Incident report queue has times listed as GMT, not correct time zone

### ISSUE THREAD

**Issue by rangerlibrarian** [burningmantech/ranger-ims-mac#75]
As I was cleaning up the incident report queue, I noticed that the incident reports were filed with the wrong timestamp (ie. its currently Friday 11am and there were reports filed Friday at 1620 as in the future).

**Comment by rangerfortress** [comment]
Sounds like I made a hash of it.  Thank you for the clean-up, and my
apologies.  I'd also like to apologize for hogging the 3rd stations when
you were trying to get in a quick log.  I should have turned it over to
you, Pronto!

Fortress

**Comment by wsanchez** [comment]
The time zone setting on the client machine effects how it is displayed.
If you don't think that's the cause, I'll need specific examples for where to look for problems.
